In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Jamestown,US,2022-06-29 16:38:14,42.0970,-79.2353,74.01,54,75,17.27
1,1,Brae,GB,2022-06-29 16:38:15,60.3964,-1.3530,58.44,84,100,18.39
2,2,Rikitea,PF,2022-06-29 16:38:15,-23.1203,-134.9692,71.73,78,73,17.49
3,3,Rundu,NaN,2022-06-29 16:38:15,-17.9333,19.7667,58.71,45,99,3.51
4,4,Ushuaia,AR,2022-06-29 16:38:09,-54.8000,-68.3000,37.02,64,20,3.44

In [3]:
# Get the data types.
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# 1. Assign the locations to an array of latitude and longitude pairs.
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weights variable to some values.
temperatures = city_data_df["Humidity"]
max_temp = temperatures.max()

# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure()

# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)

# 5. Add the heatmap layer.
fig.add_layer(heatmap_layer)
# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [9]:
# 1. Assign the locations to an array of latitude and longitude pairs.
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weights variable to some values.
temperatures = city_data_df["Humidity"]
max_temp = temperatures.max()

# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure()

# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heat_layer = gmaps.heatmap_layer(locations, weights=temps)

# 5. Add the heatmap layer.
fig.add_layer(heatmap_layer)
# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:

# 1. Assign the locations to an array of latitude and longitude pairs.
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weights variable to some values.
temperatures = city_data_df["Humidity"]
max_temp = temperatures.max()

# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in temperatures])

# 5. Add the heatmap layer.
fig.add_layer(heatmap_layer)
# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Create a Percent Cloudiness Heatmap
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"] 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Create a Wind Speed Heatmap
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [20]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
6,6,Kapaa,US,2022-06-29 16:38:16,22.0752,-159.3190,77.32,86,40,17.27
7,7,Beyneu,KZ,2022-06-29 16:38:17,45.3167,55.2000,79.39,32,41,13.35
8,8,Senj,HR,2022-06-29 16:38:17,44.9894,14.9058,86.67,63,1,2.80
15,15,Arraial Do Cabo,BR,2022-06-29 16:38:20,-22.9661,-42.0278,85.96,54,0,10.36
16,16,Albany,US,2022-06-29 16:35:51,42.6001,-73.9662,82.02,47,29,6.42
17,17,Butaritari,KI,2022-06-29 16:38:21,3.0707,172.7902,81.39,79,100,15.12
20,20,San Patricio,US,2022-06-29 16:38:22,28.0170,-97.5169,89.91,46,17,10.47
22,22,Calamar,CO,2022-06-29 16:38:23,10.2511,-74.9146,88.48,60,46,8.46
23,23,Batsfjord,NO,2022-06-29 16:38:23,70.6345,29.7185,83.98,42,20,3.44
31,31,Bubaque,GW,2022-06-29 16:38:26,11.2833,-15.8333,80.38,80,68,8.32

In [21]:
preferred_cities_df.count()

City_ID       188
City          188
Country       188
Date          188
Lat           188
Lng           188
Max Temp      188
Humidity      188
Cloudiness    188
Wind Speed    188
dtype: int64

In [23]:
preferred_cities_df.count()

City_ID       188
City          188
Country       188
Date          188
Lat           188
Lng           188
Max Temp      188
Humidity      188
Cloudiness    188
Wind Speed    188
dtype: int64

In [24]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Country       0
Date          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [25]:
preferred_cities_df.dropna()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
6,6,Kapaa,US,2022-06-29 16:38:16,22.0752,-159.3190,77.32,86,40,17.27
7,7,Beyneu,KZ,2022-06-29 16:38:17,45.3167,55.2000,79.39,32,41,13.35
8,8,Senj,HR,2022-06-29 16:38:17,44.9894,14.9058,86.67,63,1,2.80
15,15,Arraial Do Cabo,BR,2022-06-29 16:38:20,-22.9661,-42.0278,85.96,54,0,10.36
16,16,Albany,US,2022-06-29 16:35:51,42.6001,-73.9662,82.02,47,29,6.42
...,...,...,...,...,...,...,...,...,...,...
523,523,Ylojarvi,FI,2022-06-29 16:42:35,61.5563,23.5961,83.95,45,0,9.22
526,526,Los Amates,GT,2022-06-29 16:42:36,15.2667,-89.1000,82.83,74,68,3.89
528,528,Dicabisagan,PH,2022-06-29 16:42:37,17.0818,122.4157,78.55,89,100,7.49
534,534,Saint Johnsbury,US,2022-06-29 16:42:39,44.4192,-72.0151,78.73,50,40,8.05
537,537,Mitsamiouli,KM,2022-06-29 16:42:40,-11.3847,43.2844,77.29,69,20,14.97

In [26]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
6             Kapaa      US     77.32  22.0752 -159.3190
7            Beyneu      KZ     79.39  45.3167   55.2000
8              Senj      HR     86.67  44.9894   14.9058
15  Arraial Do Cabo      BR     85.96 -22.9661  -42.0278
16           Albany      US     82.02  42.6001  -73.9662
17       Butaritari      KI     81.39   3.0707  172.7902
20     San Patricio      US     89.91  28.0170  -97.5169
22          Calamar      CO     88.48  10.2511  -74.9146
23        Batsfjord      NO     83.98  70.6345   29.7185
31          Bubaque      GW     80.38  11.2833  -15.8333

In [28]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [29]:
# Dependencies and Setup
import requests
import gmaps

# Import API key
from config import g_key

In [30]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'Aap_uEBRfsoD-UYX5jtqXsPyzOp6AX7JPdJDDvkljca1vxymyjDhlOL1lhd7RR5xIuYo-WhLjdHeAYXE60cnfTnLzJVg17_XwctjOgdsShGxNRuQl9kaj9ns0YKSzcFddXxGdgeuNbAdHg7cRBkiI6QuOIE0df9DOXvoUezm1hqWe1VI7iTYbZd3VfL88WAlJGYDztG9F2xO1LVeLF-qpUuZHYwGFspbCvZHKbjxg-JBRvfCEMPvh9XH6Znf2TLXiCBnoXaYHmuGPHo_SeNoDQ39ev6YE9J-PziqNABfkCmYK_d_YQBIaPqh7AJlqolf2wsogyVmuLARUD7b4l7nCseKspeZ6mtruSqJfmX2388lmU04ynuppjpjgBXolJ9wIADVZMXgrtB-clKOKa9f_21TBaPbVGyvJrHO3F57kvK6OMLopZQxcTLDY0sv',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594360302915,
      'lng': 2.354355480291502},
     'southwest': {'lat': 48.8567380697085, 'lng': 2.351657519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'Aap_uEDxjVRc5EPK0uOe_A4qmpshnSEnExsp-sG1UBV0OM3rl6Eo5xV63caHMN7xIIh6CLKL9OqGUnwWKjidUUc48o4hH_rEVQO5jhY-e5tltvQtq-NPkik6xTNKl7r5gWLkA2jq3A2MA5313v1pmQ9OJ2bGuztIchqEc5UFI1iEAftDYst2',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['gym',
    'spa',
    'lodging',
    'night_club',
    'bar',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 332,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.85954748029151,
      'lng': 2.347782830291502},
     'southwest': {'lat': 48.85684951970851, 'lng': 2.345084869708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Britannique Hotel - Paris Centre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Centre</a>'],
     'photo_reference': 'Aap_uEA9Ooj8bOKOezhM2kS0n9sVKOXXLw8l_ODEfiiFcE4ZI8XmEloqACGwXCFnRyds89NYc0NJHwEn3Cr9e6YeY__MFv2rxrEeblgF_Aw6r55PTzCBsTdv-3g5w4dPCDrIJcQCdmH1u5cWu-s3O7AldLrogYc3Tt8jA64fWBV1iUjeK1RO',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.7,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 748,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8606342, 'lng': 2.3468978},
    'viewport': {'northeast': {'lat': 48.8617746302915,
      'lng': 2.347927730291502},
     'southwest': {'lat': 48.8590766697085, 'lng': 2.345229769708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Les Halles Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 853,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Apart&#39;hotel Les Halles Paris</a>'],
     'photo_reference': 'Aap_uEDtVGyz2vJd06lc4F3SjFhG9ZlCZ26Mzq5dlIMpcnu30nKWCeguH8hCwju-BEUrrNd2fhRqaa3QXrjT1qia8imlo9-so3TEXd3wsD7Iii6EeD9wV4T7VqWSC6UDP5bseT_y5CMybdVcTBAQgD89qVyfOnxfRMj-K-YWmjzDR3lC-niq',
     'width': 1280}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['city_hall',
    'local_government_office',
    'lodging',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 913,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607658, 'lng': 2.3465318},
    'viewport': {'northeast': {'lat': 48.8620584302915,
      'lng': 2.347692880291501},
     'southwest': {'lat': 48.85936046970851, 'lng': 2.344994919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Novotel Paris Les Halles',
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'],
     'photo_reference': 'Aap_uEDizuJZJd91GgL8uHmtmW6yZPNP4DUyB2mriU-TaZgtwEzuqFVgMoJ1XGYTYSx_tA_6rSCpPXPKmPf16q3o3_mghYOV-hpf4Dn1HSP-X-facM9DSp5iK9YEXjQSqV9XLXT914cHL2U6U2ezdmVXV7l039MZJqf_h2fJ55goq4ZB5rsy',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8J Paris, France',
    'global_code': '8FW4V86W+8J'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2530,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.860352, 'lng': 2.3440948},
    'viewport': {'northeast': {'lat': 48.86165553029149,
      'lng': 2.345549080291502},
     'southwest': {'lat': 48.8589575697085, 'lng': 2.342851119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Hôtel Ducs de Bourgogne</a>'],
     'photo_reference': 'Aap_uECUGleqNPoHyFUkhZv4AJQHvTnXBJvGgVNYgUrk_nwgedpjBJFMWP5Ndrt3_o3cgzGa9GrKtuD6faHm0Lae9hehWa8T6Qy6w7OijPjBtbB2qH_A8SGlhg8Kw_vHcuNuHbAo7HeEEqYKZRt8bdyqxxauO397zXM6QrVEZ9Afr9Bc3Gpg',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 300,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569076302915,
      'lng': 2.342319280291502},
     'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Saint-Germain-des-Prés Paris (Apart hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113188832595116816387">Citadines Saint-Germain-des-Prés Paris (Apart Hotel Paris)</a>'],
     'photo_reference': 'Aap_uEArgdQo2FS7ec-Idzo1JMr6DkqRH7QBUkASM1yMD2CkIJ4qXDF4bnrZJ647bgvYhUCF4yo1tTccZrLonhCB21Tt4QFSfNFZ2sZPnBFiSIXA_HBetitrafKfCNjZolib-xy3auzKB9yNRf3a803N4SmXfd8S61h2DWnG_VCMxIkjcgK8',
     'width': 6720}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['city_hall',
    'local_government_office',
    'lodging',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 744,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8524547, 'lng': 2.3472064},
    'viewport': {'northeast': {'lat': 48.8538838802915,
      'lng': 2.348601530291502},
     'southwest': {'lat': 48.8511859197085, 'lng': 2.345903569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Esmeralda',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1960,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106443224837840180239">Fraz A. Khan</a>'],
     'photo_reference': 'Aap_uEDzuM45sxrvinKc3ZN3PPVG4RrfdJ1_cu45gbiKE1Z8xsTfri8EupyhlvBEw1NPGL-fbzC1cxT0lvV8spKcB5XmXXSkvv6HSQOrkJaGC-YzlHdO0rfBH1_GOqnQQxzVruvU7wBlLUdGCaZWV8Osmstf947pEhZJUzpYp9tz3bhlMqTX',
     'width': 4032}],
   'place_id': 'ChIJO_g_H-Fx5kcRmaabUHA3dT4',
   'plus_code': {'compound_code': 'V82W+XV Paris, France',
    'global_code': '8FW4V82W+XV'},
   'rating': 4.1,
   'reference': 'ChIJO_g_H-Fx5kcRmaabUHA3dT4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 168,
   'vicinity': '4 Rue Saint-Julien le Pauvre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8530901, 'lng': 2.3447174},
    'viewport': {'northeast': {'lat': 48.8544535802915,
      'lng': 2.345997680291501},
     'southwest': {'lat': 48.85175561970851, 'lng': 2.343299719708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Albe Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1152,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117571951379278191466">Albe Hotel Saint Michel</a>'],
     'photo_reference': 'Aap_uEDZhf9XQSjhkUAh4ts9kDj9zRpvdwSsaibaHAmcZ_lH1ntIdXd2xczLBZ8Qr3XsEmciE5vi9PT1JatilG4XQCxXAX8rIXFmsFUWFNHN4HCKeqhXapWX6sSHWs63x8d2BB766tDC1gUlIXZ0QfbKy93hEd5N23k_MT93Pu8ek5yTejaT',
     'width': 1600}],
   'place_id': 'ChIJ8R5-hOBx5kcRsCOdfj8GLeY',
   'plus_code': {'compound_code': 'V83V+6V Paris, France',
    'global_code': '8FW4V83V+6V'},
   'rating': 4.4,
   'reference': 'ChIJ8R5-hOBx5kcRsCOdfj8GLeY',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 368,
   'vicinity': '1 Rue de la Harpe, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8532403, 'lng': 2.3457375},
    'viewport': {'northeast': {'lat': 48.85462748029149,
      'lng': 2.347175730291502},
     'southwest': {'lat': 48.8519295197085, 'lng': 2.344477769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Les Rives de Notre-Dame Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116242575283063930652">Michael Scholz</a>'],
     'photo_reference': 'Aap_uECsba38PESoIGzCtRG3rUEf24GHnddEsuiE-p587Iyrly4tkm6OjY_hhmxISxFoNKkjtRFbzogftZJU8AhRS-J1ijE2ccLS3aRjFHCMfzHq7TmhtZ3KQHUPb35-mUuGDLkgfafvTTFFGYaUmMq2Mld0nZL1LTwYZa0UEdLrwi9OkvZr',
     'width': 6048}],
   'place_id': 'ChIJl7vs8-Bx5kcRfIQzq_4_XmU',
   'plus_code': {'compound_code': 'V83W+77 Paris, France',
    'global_code': '8FW4V83W+77'},
   'rating': 4.5,
   'reference': 'ChIJl7vs8-Bx5kcRfIQzq_4_XmU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 100,
   'vicinity': '15 Quai Saint-Michel, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.85184049999999, 'lng': 2.3448082},
    'viewport': {'northeast': {'lat': 48.8531470802915,
      'lng': 2.346121880291502},
     'southwest': {'lat': 48.8504491197085, 'lng': 2.343423919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel 4 étoiles Parc Saint-Séverin Paris 5ème - Esprit de France',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2362,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107542132357877294567">Hôtel 4 étoiles Parc Saint Séverin Paris 5ème - Esprit de France</a>'],
     'photo_reference': 'Aap_uEBUD4g_KzqXgpzo5PEJ-UvTcDjinKIXxEkZIRmMq6KgF_zkmnQzsdFzklHwAQyelH5ghTs6ZZCfy-rRP_a1JYcNCba17GSMtmsaE9bBFUCFdTRD4eRAqjmDKnaPRcfP7-WhXvh84MGNoF10p5cBrqXoyI2r9YYfLRu14svWw04d23ol',
     'width': 3776}],
   'place_id': 'ChIJ9--kuuBx5kcRojwQ1yEK2cY',
   'plus_code': {'compound_code': 'V82V+PW Paris, France',
    'global_code': '8FW4V82V+PW'},
   'rating': 4.6,
   'reference': 'ChIJ9--kuuBx5kcRojwQ1yEK2cY',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 181,
   'vicinity': '22 Rue de la Parcheminerie, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8518743, 'lng': 2.3463436},
    'viewport': {'northeast': {'lat': 48.8532481802915,
      'lng': 2.347596830291502},
     'southwest': {'lat': 48.8505502197085, 'lng': 2.344898869708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Henri IV Rive Gauche',
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110759590658386679133">François TAPIEZO ART</a>'],
     'photo_reference': 'Aap_uECgUNm9Eyo-UAWjHrlwN6l8_GdlvwXU7p_IkVcy0yyb15_Ig0K4rf9mOGH6_-xNg3bcTRn5trwGGJ1oQA4s2z9r6kihv-G3jFbrYmLU1PZJ6_1LwpaUt1q6WRBDsR9267cBQPGCwI88qD1ybils8kiNclGtTXQFk_EKd3LCCxqS6ubq',
     'width': 4032}],
   'place_id': 'ChIJ2a4f2-Bx5kcR40Wl3uv_53Y',
   'plus_code': {'compound_code': 'V82W+PG Paris, France',
    'global_code': '8FW4V82W+PG'},
   'rating': 4.5,
   'reference': 'ChIJ2a4f2-Bx5kcR40Wl3uv_53Y',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 160,
   'vicinity': 'Rue Saint-Jacques, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8600866, 'lng': 2.3533543},
    'viewport': {'northeast': {'lat': 48.86148808029149,
      'lng': 2.354740780291502},
     'southwest': {'lat': 48.85879011970849, 'lng': 2.352042819708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Beaubourg',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3435,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115421447635584539926">Hôtel Beaubourg</a>'],
     'photo_reference': 'Aap_uEAKVn2FKfEzYK-jDRvQpVlZiBKC5ckg8FcsNl7RGsUy7CNYhO0eVAg1u9Rsaq4e9Ag8tudClLX4St4hGb1QnCZY-7Foss9HGHUNKnsix0zWBnV0GXgsriDtxLCipWPvg3-fNUYNR_jEQZg1iIv-JheXjZWDW7NUTJN6ZxY-wfjedr2U',
     'width': 5153}],
   'place_id': 'ChIJCdHKjhxu5kcR0YtyGr7Vftc',
   'plus_code': {'compound_code': 'V963+28 Paris, France',
    'global_code': '8FW4V963+28'},
   'rating': 4.2,
   'reference': 'ChIJCdHKjhxu5kcR0YtyGr7Vftc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 156,
   'vicinity': '11 Rue Simon le Franc, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.859876, 'lng': 2.347049},
    'viewport': {'northeast': {'lat': 48.86117138029149,
      'lng': 2.348348980291501},
     'southwest': {'lat': 48.8584734197085, 'lng': 2.345651019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': "Hôtel Des Ducs D'Anjou",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1400,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115209143941459061727">Hotel Des Ducs D&#39;Anjou</a>'],
     'photo_reference': 'Aap_uEAURsxlZ0k_oC9DgY9EfJrhn1CJiV1wF30OQGE4dqbG6DhLGZjbIjJUJMx8C35jGjMtNRTm4QLnq6SM9tthsZMymRZ93OA9dy5q18SA_JoOBgTTVYNjbJC3tHdHbO3egMuUglZuoUOjlr2i-S7vfeAFTDFSPBiyFkQU5tL09315cOt-',
     'width': 1352}],
   'place_id': 'ChIJ9ekWGR9u5kcRsS8j5TnWeSE',
   'plus_code': {'compound_code': 'V85W+XR Paris, France',
    'global_code': '8FW4V85W+XR'},
   'rating': 3.9,
   'reference': 'ChIJ9ekWGR9u5kcRsS8j5TnWeSE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 328,
   'vicinity': '1 Rue Sainte-Opportune, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8515237, 'lng': 2.3486679},
    'viewport': {'northeast': {'lat': 48.8529256302915,
      'lng': 2.349962130291502},
     'southwest': {'lat': 48.8502276697085, 'lng': 2.347264169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Maison Colbert Member of Meliá Collection',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3656,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102194778927204133336">Hotel Maison Colbert Member of Meliá Collection</a>'],
     'photo_reference': 'Aap_uEAKX1JQU1bhPDPQQPxSUyp07WS9tRJyDbe4HkAh_noG9wDIsjar4hpClHsX_g_NEWj5eHC-NnnjobpBfRgu7fn70Qd4Mwk1eEFj0AsNUjUaEmx9hjEoRsmnpvAZk2U763rq5NVZoKWnBvu0xsRnGUh-6bX3cBeo5xL5noZp14juex0u',
     'width': 3543}],
   'place_id': 'ChIJI3vbSOFx5kcR84E4IeL2LqI',
   'plus_code': {'compound_code': 'V82X+JF Paris, France',
    'global_code': '8FW4V82X+JF'},
   'rating': 4.4,
   'reference': 'ChIJI3vbSOFx5kcR84E4IeL2LqI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 13,
   'vicinity': "7 Rue de l'Hôtel Colbert, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8499446, 'lng': 2.346247699999999},
    'viewport': {'northeast': {'lat': 48.8513264802915,
      'lng': 2.347622530291501},
     'southwest': {'lat': 48.8486285197085, 'lng': 2.344924569708497}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Home Latin',
   'photos': [{'height': 4080,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113966656287531023757">Ioan Mihael</a>'],

In [31]:
len(hotels["results"])

20

In [46]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params = {
        "location": f"{lat},{lng}",
        "radius": 5000,
        "types" : "hotel",
        "key": g_key
    }

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    #hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError): print("Hotel not found... skipping.")

Hotel not found... skipping.

In [47]:
hotel_df.head()

               City Country  Max Temp      Lat       Lng     Hotel Name
6             Kapaa      US     77.32  22.0752 -159.3190         Kapaʻa
7            Beyneu      KZ     79.39  45.3167   55.2000         Beyneu
8              Senj      HR     86.67  44.9894   14.9058           Senj
15  Arraial Do Cabo      BR     85.96 -22.9661  -42.0278      Cabo Frio
16           Albany      US     82.02  42.6001  -73.9662  Voorheesville

In [48]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [49]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [51]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [52]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))